### ISSUE TITLE
mySQL Server Port Tunnel

### ISSUE THREAD

**Issue by nugentmichael1** [FS-CSCI150-F21/FS-CSCI150-F21-Team1#13]
Ensure mySQL server can be reached on host as Pi will directly access it on port other than 80.  Ngrok?

**Comment by lhn1703** [comment]
@nugentmichael1 I would like your assistance with setting up a port forwarding, since most of our codebase is designed around mysql connection. I have completed the wait time algorithm that pulls data from the open orders table, now just need to integrate and allow the auxiliary device to directly connect to the main server mysql's port.

**Comment by lhn1703** [comment]
install mysql-connector-python and remote access to database works.
